"""
batch_enhance_descriptions.py
-----------------------------
P0/P1 層級的批量優化處理框架。

用法：
  python scripts/batch_enhance_descriptions.py --candidates-file data/p0_candidates.json
  python scripts/batch_enhance_descriptions.py --candidates-file data/p0_candidates.json --batch-size 10 --dry-run
  python scripts/batch_enhance_descriptions.py --candidates-file data/p0_candidates.json --output data/p0_batch1_enhancements.json
"""

import json
import argparse
import re
from pathlib import Path
from datetime import datetime, timezone
from collections import defaultdict
from typing import Any

try:
    from anthropic import Anthropic
except ImportError as exc:
    Anthropic = None
    IMPORT_ERROR = exc
else:
    IMPORT_ERROR = None

from quality_check import load_nodes, score_description, score_node


BASE_DIR = Path(__file__).parent.parent
CANDIDATES_DEFAULT = BASE_DIR / "data" / "p0_candidates.json"


def load_candidates(path: Path):
    """Load candidates from JSON file generated by generate_p0_candidates.py"""
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return data.get("candidates", [])


def build_enhancement_prompt(node_dict: dict, candidate: dict) -> str:
    """
    構建針對單一節點的優化提示詞。
    
    基於試點 20 個節點的成功模式，強化 WHAT/SIGNIFICANCE/BRIDGE。
    """
    diagnostics_str = "\n  - ".join(candidate.get("diagnostics", []))
    
    prompt = f"""You are an expert knowledge graph curator improving node descriptions for a multidisciplinary learning platform.

CURRENT STATUS:
- Node: {candidate['label']} ({candidate['node_id']})
- Type: {candidate['type']} | Domains: {', '.join(candidate['domain'])}
- Quality Score: {candidate['current_score']['description']}/10 (Description)
- Key Issues: {diagnostics_str}

CURRENT DESCRIPTION:
{candidate['original_description']}

OPTIMIZATION TASK:
Improve the English description by strengthening these three dimensions:

1. **WHAT (Definition)**: Make the opening sentence crystal-clear about what this concept/person/event IS.
   - Use declarative language: "X is..." or "X refers to..."
   - Include essential characteristics in 1-2 sentences
   - Avoid vague or circular definitions

2. **SIGNIFICANCE (Impact)**: Emphasize why this matters across disciplines or history.
   - Highlight transformative contributions, breakthroughs, or foundational importance
   - Connect to broader intellectual or practical consequences
   - Use strong, precise language (not hyperbolic)

3. **BRIDGE (Cross-domain)**: If applicable, show connections to other fields.
   - Mention specific domains affected (e.g., "philosophy," "engineering," "medicine")
   - Explain HOW this concept bridges disciplines
   - Avoid generic claims; be specific

CONSTRAINTS:
- Maintain 120-240 words
- Preserve key terminology and scientific accuracy
- Keep a scholarly tone appropriate for university learners
- Return ONLY the improved description text, no metadata or explanation

IMPROVED DESCRIPTION:"""
    
    return prompt


def call_llm_for_candidate(client, model: str, prompt: str, max_tokens: int = 300) -> str:
    """Call Anthropic API to generate improved description"""
    message = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    return message.content[0].text.strip()


def process_batch(
    candidates: list,
    batch_start: int,
    batch_size: int,
    model: str,
    dry_run: bool = False,
    temperature: float = 0.2
) -> list:
    """
    Process a batch of candidates: generate, score, and validate.
    
    Returns list of enhanced records with before/after scoring.
    """
    batch_end = min(batch_start + batch_size, len(candidates))
    batch_candidates = candidates[batch_start:batch_end]
    
    print(f"\n{'='*70}")
    print(f"BATCH [{batch_start+1}-{batch_end}]")
    print(f"{'='*70}")
    
    # Load all nodes for re-scoring
    all_nodes = load_nodes()
    node_lookup = {n["id"]: n for n in all_nodes}
    
    results = []
    
    if not Anthropic:
        print("ERROR: Anthropic not installed")
        return []
    
    client = Anthropic()
    
    for i, candidate in enumerate(batch_candidates, start=batch_start + 1):
        node_id = candidate["node_id"]
        print(f"\n[{i}/{len(candidates)}] {candidate['label']} ({node_id})", end=" ... ")
        
        if dry_run:
            print("[DRY RUN]")
            prompt = build_enhancement_prompt(node_dict={}, candidate=candidate)
            print(f"\nPrompt preview (first 200 chars):\n{prompt[:200]}...")
            results.append({
                "node_id": node_id,
                "status": "dry_run",
                "prompt_preview": prompt[:300]
            })
            continue
        
        try:
            # Build and send prompt
            prompt = build_enhancement_prompt(node_dict={}, candidate=candidate)
            enhanced_desc = call_llm_for_candidate(client, model, prompt)
            
            # Temporarily create enhanced node for scoring
            enhanced_node = node_lookup[node_id].copy()
            enhanced_node["description"] = enhanced_desc
            
            # Score before/after
            original_desc_result = score_description(node_lookup[node_id])
            enhanced_desc_result = score_description(enhanced_node)
            original_total = score_node(node_lookup[node_id], node_lookup)["total_score"]
            enhanced_total = score_node(enhanced_node, node_lookup)["total_score"]
            
            improvement = enhanced_total - original_total
            print(f"✓ Score: {original_total:.1f} → {enhanced_total:.1f} ({improvement:+.1f})")
            
            results.append({
                "node_id": node_id,
                "label": candidate["label"],
                "status": "completed",
                "before": {
                    "description_score": original_desc_result["total"],
                    "total_score": original_total,
                    "diagnostics": original_desc_result["diagnostics"]
                },
                "after": {
                    "description_score": enhanced_desc_result["total"],
                    "total_score": enhanced_total,
                    "diagnostics": enhanced_desc_result["diagnostics"]
                },
                "improvement": {
                    "score_delta": improvement,
                    "description_delta": enhanced_desc_result["total"] - original_desc_result["total"]
                },
                "enhanced_description": enhanced_desc,
                "original_description": candidate["original_description"]
            })
            
        except Exception as e:
            print(f"✗ ERROR: {e}")
            results.append({
                "node_id": node_id,
                "status": "error",
                "error": str(e)
            })
    
    return results


def main():
    parser = argparse.ArgumentParser(description="Batch enhancement for P0/P1 candidates")
    parser.add_argument("--candidates-file", type=Path, default=CANDIDATES_DEFAULT,
                        help="Path to candidates JSON")
    parser.add_argument("--batch-size", type=int, default=10,
                        help="Nodes per batch (for pacing and review)")
    parser.add_argument("--batch-num", type=int, default=1,
                        help="Which batch to process (1-indexed)")
    parser.add_argument("--model", type=str, default="claude-sonnet-4-6",
                        help="Anthropic model")
    parser.add_argument("--dry-run", action="store_true",
                        help="Generate prompts without calling LLM")
    parser.add_argument("--output", type=Path, default=None,
                        help="Output JSON path (auto-generated if not provided)")
    args = parser.parse_args()
    
    # Load candidates
    candidates = load_candidates(args.candidates_file)
    print(f"Loaded {len(candidates)} candidates from {args.candidates_file.name}")
    
    # Calculate batch range
    batch_start = (args.batch_num - 1) * args.batch_size
    batch_end = min(batch_start + args.batch_size, len(candidates))
    
    if batch_start >= len(candidates):
        print(f"ERROR: batch_num={args.batch_num} is out of range (max={len(candidates) // args.batch_size + 1})")
        return
    
    # Process batch
    results = process_batch(
        candidates=candidates,
        batch_start=batch_start,
        batch_size=args.batch_size,
        model=args.model,
        dry_run=args.dry_run
    )
    
    # Generate output filename
    if not args.output:
        candidates_name = args.candidates_file.stem  # "p0_candidates" → "p0"
        batch_suffix = f"_batch{args.batch_num}"
        args.output = BASE_DIR / "data" / f"{candidates_name}{batch_suffix}_enhancements.json"
    
    # Save results
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump({
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "batch": {
                "number": args.batch_num,
                "start": batch_start,
                "end": batch_end,
                "size": args.batch_size
            },
            "candidates_source": args.candidates_file.name,
            "total_candidates": len(candidates),
            "batch_results": results,
            "summary": {
                "total_processed": len([r for r in results if r["status"] in ["completed", "dry_run"]]),
                "completed": len([r for r in results if r["status"] == "completed"]),
                "errors": len([r for r in results if r["status"] == "error"]),
                "avg_score_improvement": (
                    sum(r["improvement"]["score_delta"] for r in results if r["status"] == "completed") /
                    len([r for r in results if r["status"] == "completed"])
                    if [r for r in results if r["status"] == "completed"] else 0
                )
            }
        }, f, indent=2, ensure_ascii=False)
    
    print(f"\n{'='*70}")
    print(f"Results saved to: {args.output}")
    print(f"{'='*70}")


if __name__ == "__main__":
    main()
